name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run webpack

      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
          repository: bakabird/imgui-server
          token: ${{ secrets.IMGUITS }}
          path: imgui-server

      - name: Copy www directory to imgui-server
        run: |
          cp -r www/* imgui-server/www

      - name: Push changes to my other private repo
        run: |
          cd imgui-server
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add www
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update www directory"
            git push
          fi
