name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run webpack

      - name: Sync files to another repository
        env:
          GITHUB_TOKEN: ${{ secrets.IMGUI-TS }}
          TARGET_REPO: imgui-server
        run: |
          git clone https://github.com/${{ github.repository_owner }}/${{ env.TARGET_REPO }}.git target_repo
          cp -r www target_repo/www
          cd target_repo
          git add www
          git commit -m "Sync www folder"
          git push origin main
